version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q123
      - POSTGRES_DB=itsware
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  itsware:
    container_name: itsware
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    volumes:
      - itsware:/usr/src/itsware/
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

volumes:
  itsware:
  postgres:

networks:
  backend:
    driver: bridge